kind: pipeline
name: default

steps:
- name: build
  image: ohdarling/node-builder:latest
  environment:
    SSH_KEY:
      from_secret: ssh_key
    http_proxy:
      from_secret: http_proxy
  commands:
    - mkdir -p /root/.ssh/
    - echo "$$SSH_KEY" > /root/.ssh/id_rsa
    - chmod -R 600 /root/.ssh/
    - rm -f DXYArea.csv
    - wget https://raw.githubusercontent.com/BlankerL/DXY-2019-nCoV-Data/master/csv/DXYArea.csv
    - node build.js
    - git add public/data.json
    - git add DXYArea.csv
    - git remote add github git@github.com:ohdarling/2019-nCoV-Charts.git
    - git push github master
